### ISSUE TITLE
refresh-secrets removes user entries in sops.yaml

### ISSUE THREAD

**Issue by ArthurClemens** [tarasglek/github-to-sops#20]
After setting up `.sops.yaml` with `--github-users ArthurClemens `, the following file is created, as expected:

```
creation_rules:
  - key_groups:
      - age:
        # Generated by `/opt/homebrew/bin/github-to-sops import-keys --github-users ArthurClemens--key-types ssh-ed25519 --format sops` https://github.com/tarasglek/github-to-sops
        - agemysshkey # ArthurClemens
# EOF
```

After that, `github-to-sops refresh-secrets` results in:

```
creation_rules:
  - key_groups:
      - age:
        # Generated by `/opt/homebrew/bin/github-to-sops import-keys --inplace-edit .sops.yaml` https://github.com/tarasglek/github-to-sops
# EOF
```

I am no longer listed and can no longer access the secrets.
